name: Secrets

on:
  build:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Run a script
        evn:
                FIRST_SECRATE: ${{ secrets.FIRST_SECRATE}}
      - run: echo "This is first secrate key $FIRST_SECRATE"
